import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import SideberMenuMain from './SideberMenuMain';
export default function SideBar({ headleOpen, isOpen }) {
    const [active, setActive] = React.useState(false);
    return (_jsx("div", { className: 'flex', children: _jsxs("div", { className: `${isOpen ? `w-72` : `w-20`} fixed duration-300 h-screen bg-white border-1 z-20  ${active ? `w-72` : `w-20`}`, onMouseEnter: () => setActive(true), onMouseLeave: () => setActive(false), children: [_jsxs("div", { className: 'h-28', children: [isOpen ? (_jsx("div", { className: ' absolute cursor-pointer rounded-full -right-4 top-6 bg-white z-50', onClick: () => {
                                headleOpen(false);
                                setActive(false);
                            }, children: _jsxs("svg", { className: "h-8 w-8 text-red-500", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", children: ["  ", _jsx("circle", { cx: "12", cy: "12", r: "10" }), "  ", _jsx("polyline", { points: "12 8 8 12 12 16" }), "  ", _jsx("line", { x1: "16", y1: "12", x2: "8", y2: "12" })] }) })) : (_jsx("div", { className: ' absolute cursor-pointer rounded-full -right-4 top-6 bg-white  z-50', onClick: () => headleOpen(true), children: _jsxs("svg", { className: "h-8 w-8 text-red-500", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", children: ["  ", _jsx("circle", { cx: "12", cy: "12", r: "10" }), "  ", _jsx("polyline", { points: "12 16 16 12 12 8" }), "  ", _jsx("line", { x1: "8", y1: "12", x2: "16", y2: "12" })] }) })), _jsxs("div", { className: 'inline-flex', children: [_jsx("div", { className: `${isOpen || active ? `block` : `hidden`} `, children: _jsx("img", { alt: "Logo", src: `${import.meta.env.VITE_APP_IMG_LOGO_URL}/INTRANET/DMZ/Asset/Logo/Logo_TRR_Lin_TH.png`, className: "py-2 px-8" }) }), _jsx("div", { className: `${isOpen || active ? `hidden` : `block`} `, children: _jsx("img", { alt: "Logo", src: `${import.meta.env.VITE_APP_IMG_LOGO_URL}/EVI/DEV/Logo/TRR.png`, className: "h-[40px] m-3" }) })] })] }), _jsx(SideberMenuMain, { isOpen: isOpen || active })] }) }));
}
